// Food Stories - Educational content about Chinese cuisine

export interface FoodStory {
  id: string;
  slug: string;
  title: string;
  titleChinese: string;
  category: string;
  excerpt: string;
  content: string;
  author: string;
  date: string;
  readTime: string;
  image: string;
  type: 'article' | 'video';
  videoUrl?: string;
  tags: string[];
}

export const foodStories: FoodStory[] = [
  // RECIPE HISTORY
  {
    id: '1',
    slug: 'history-of-peking-duck',
    title: 'The Imperial Legacy of Peking Duck',
    titleChinese: '北京烤鸭的皇家传承',
    category: 'Recipe History',
    excerpt: 'From imperial courts to your table - the fascinating 600-year journey of China\'s most famous dish.',
    content: 'Peking Duck dates back to the Yuan Dynasty...',
    author: 'Chef Chen Wei',
    date: '2024-12-15',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80',
    type: 'article',
    tags: ['Peking Duck', 'History', 'Imperial Cuisine'],
  },
  {
    id: '2',
    slug: 'story-of-dim-sum',
    title: 'Dim Sum: The Heart-Touching Tradition',
    titleChinese: '点心：触动心灵的传统',
    category: 'Recipe History',
    excerpt: 'Discover how dim sum evolved from tea house snacks to a beloved culinary art form.',
    content: 'Dim sum, which means "touch the heart"...',
    author: 'Chef Chen Wei',
    date: '2024-12-10',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&q=80',
    type: 'article',
    tags: ['Dim Sum', 'History', 'Tea Culture'],
  },
  {
    id: '3',
    slug: 'origins-of-kung-pao',
    title: 'Kung Pao Chicken: A Sichuan Classic',
    titleChinese: '宫保鸡丁的四川传奇',
    category: 'Recipe History',
    excerpt: 'Named after a Qing Dynasty official, this spicy dish has a rich history spanning centuries.',
    content: 'The dish was named after Ding Baozhen...',
    author: 'Chef Chen Wei',
    date: '2024-12-01',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
    type: 'article',
    tags: ['Kung Pao', 'Sichuan', 'History'],
  },

  // COOKING TIPS
  {
    id: '4',
    slug: 'perfect-fried-rice',
    title: 'Chef\'s Secret to Perfect Fried Rice',
    titleChinese: '大厨的完美炒饭秘诀',
    category: 'Cooking Tips',
    excerpt: 'Learn the professional techniques that make restaurant fried rice fluffy, flavorful, and never greasy.',
    content: 'The key to great fried rice is day-old rice...',
    author: 'Chef Chen Wei',
    date: '2024-11-28',
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80',
    type: 'article',
    tags: ['Fried Rice', 'Technique', 'Tips'],
  },
  {
    id: '5',
    slug: 'wok-mastery-video',
    title: 'Mastering the Wok: Heat Control',
    titleChinese: '掌握炒锅：火候控制',
    category: 'Cooking Tips',
    excerpt: 'Watch Chef Chen demonstrate proper wok technique and heat management for authentic stir-fry.',
    content: 'Video tutorial on wok cooking...',
    author: 'Chef Chen Wei',
    date: '2024-11-25',
    readTime: '12 min',
    image: 'https://images.unsplash.com/photo-1596040033229-a0b3b1fea2b8?w=800&q=80',
    type: 'video',
    videoUrl: 'https://youtube.com/watch?v=example',
    tags: ['Wok', 'Technique', 'Video'],
  },
  {
    id: '6',
    slug: 'dumpling-folding-techniques',
    title: '7 Ways to Fold Dumplings Like a Pro',
    titleChinese: '7种专业饺子包法',
    category: 'Cooking Tips',
    excerpt: 'Master traditional dumpling folding techniques from simple to advanced pleating patterns.',
    content: 'Each fold has a purpose and meaning...',
    author: 'Chef Chen Wei',
    date: '2024-11-20',
    readTime: '10 min read',
    image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800&q=80',
    type: 'article',
    tags: ['Dumplings', 'Technique', 'Folding'],
  },

  // HEALTH & NUTRITION
  {
    id: '7',
    slug: 'health-benefits-chinese-tea',
    title: 'The Healing Power of Chinese Tea',
    titleChinese: '中国茶的养生功效',
    category: 'Health & Nutrition',
    excerpt: 'Explore the health benefits of traditional Chinese teas from green to pu-erh.',
    content: 'Chinese tea has been used medicinally for thousands of years...',
    author: 'Chef Chen Wei',
    date: '2024-11-15',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=800&q=80',
    type: 'article',
    tags: ['Tea', 'Health', 'Wellness'],
  },
  {
    id: '8',
    slug: 'nutritional-benefits-tofu',
    title: 'Why Tofu is a Superfood',
    titleChinese: '豆腐：超级食品',
    category: 'Health & Nutrition',
    excerpt: 'Discover the protein-rich benefits of tofu and why it\'s been a staple for thousands of years.',
    content: 'Tofu is an excellent source of plant-based protein...',
    author: 'Chef Chen Wei',
    date: '2024-11-10',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1542528180-a1208c5169a5?w=800&q=80',
    type: 'article',
    tags: ['Tofu', 'Health', 'Protein'],
  },
  {
    id: '9',
    slug: 'balance-of-five-flavors',
    title: 'The Balance of Five Flavors in Chinese Cuisine',
    titleChinese: '中餐的五味平衡',
    category: 'Health & Nutrition',
    excerpt: 'Learn how traditional Chinese cooking balances sweet, sour, bitter, spicy, and salty for optimal health.',
    content: 'The five flavors correspond to five elements...',
    author: 'Chef Chen Wei',
    date: '2024-11-05',
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=800&q=80',
    type: 'article',
    tags: ['Five Flavors', 'Health', 'Balance'],
  },

  // FOOD CULTURE
  {
    id: '10',
    slug: 'chinese-new-year-dishes',
    title: 'Lucky Foods for Chinese New Year',
    titleChinese: '新年吉祥菜',
    category: 'Food Culture',
    excerpt: 'Discover the symbolic meanings behind traditional dishes served during Chinese New Year celebrations.',
    content: 'Each dish carries auspicious meaning...',
    author: 'Chef Chen Wei',
    date: '2024-12-20',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&q=80',
    type: 'article',
    tags: ['New Year', 'Traditions', 'Culture'],
  },
  {
    id: '11',
    slug: 'tea-ceremony-etiquette',
    title: 'The Art of Chinese Tea Ceremony',
    titleChinese: '中国茶道艺术',
    category: 'Food Culture',
    excerpt: 'Master the graceful rituals and etiquette of traditional Chinese tea service.',
    content: 'The tea ceremony is a meditation...',
    author: 'Chef Chen Wei',
    date: '2024-11-30',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=800&q=80',
    type: 'article',
    tags: ['Tea', 'Ceremony', 'Culture'],
  },
  {
    id: '12',
    slug: 'chopsticks-etiquette',
    title: 'Chopsticks Etiquette: Do\'s and Don\'ts',
    titleChinese: '筷子礼仪',
    category: 'Food Culture',
    excerpt: 'Navigate Chinese dining with confidence - essential chopstick etiquette every diner should know.',
    content: 'Proper chopstick use shows respect...',
    author: 'Chef Chen Wei',
    date: '2024-11-22',
    readTime: '4 min read',
    image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800&q=80',
    type: 'article',
    tags: ['Etiquette', 'Chopsticks', 'Dining'],
  },

  // SEASONAL SPECIALS
  {
    id: '13',
    slug: 'winter-warming-soups',
    title: 'Winter Warming Soups',
    titleChinese: '冬季养生汤',
    category: 'Seasonal Specials',
    excerpt: 'Nourishing Chinese soups perfect for cold winter days, featuring seasonal ingredients.',
    content: 'Winter is the season for rich, warming broths...',
    author: 'Chef Chen Wei',
    date: '2024-12-18',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=800&q=80',
    type: 'article',
    tags: ['Winter', 'Soup', 'Seasonal'],
  },
  {
    id: '14',
    slug: 'spring-vegetables',
    title: 'Spring\'s Fresh Vegetables in Chinese Cooking',
    titleChinese: '春季时蔬',
    category: 'Seasonal Specials',
    excerpt: 'Celebrate spring with tender greens and fresh vegetables in traditional Chinese preparations.',
    content: 'Spring brings the most tender vegetables...',
    author: 'Chef Chen Wei',
    date: '2024-11-12',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80',
    type: 'article',
    tags: ['Spring', 'Vegetables', 'Seasonal'],
  },
  {
    id: '15',
    slug: 'summer-cold-dishes',
    title: 'Refreshing Summer Cold Dishes',
    titleChinese: '夏季凉菜',
    category: 'Seasonal Specials',
    excerpt: 'Beat the heat with traditional Chinese cold appetizers perfect for summer dining.',
    content: 'Cold dishes are perfect for hot weather...',
    author: 'Chef Chen Wei',
    date: '2024-11-08',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800&q=80',
    type: 'article',
    tags: ['Summer', 'Cold Dishes', 'Seasonal'],
  },

  // CHEF'S SECRETS
  {
    id: '16',
    slug: 'secret-to-crispy-skin',
    title: 'The Secret to Perfectly Crispy Skin',
    titleChinese: '完美脆皮的秘密',
    category: "Chef's Secrets",
    excerpt: 'Chef Chen reveals his technique for achieving that coveted crispy exterior on duck and pork.',
    content: 'The secret is in the drying process and heat control...',
    author: 'Chef Chen Wei',
    date: '2024-12-05',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&q=80',
    type: 'article',
    tags: ['Technique', 'Crispy', 'Chef Tips'],
  },
  {
    id: '17',
    slug: 'secret-sauce-recipes',
    title: 'Behind Our Signature Sauces',
    titleChinese: '我们招牌酱料的秘密',
    category: "Chef's Secrets",
    excerpt: 'A peek into the complex flavor profiles and techniques behind our most popular sauces.',
    content: 'A great sauce can make or break a dish...',
    author: 'Chef Chen Wei',
    date: '2024-11-18',
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&q=80',
    type: 'article',
    tags: ['Sauces', 'Flavors', 'Secrets'],
  },
  {
    id: '18',
    slug: 'making-xiao-long-bao-video',
    title: 'How We Make Xiao Long Bao (Video)',
    titleChinese: '小笼包制作过程',
    category: "Chef's Secrets",
    excerpt: 'Watch our chefs craft perfect soup dumplings from scratch - a delicate art requiring years of practice.',
    content: 'Video demonstration of dumpling making...',
    author: 'Chef Chen Wei',
    date: '2024-11-14',
    readTime: '15 min',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&q=80',
    type: 'video',
    videoUrl: 'https://youtube.com/watch?v=example',
    tags: ['Xiao Long Bao', 'Video', 'Technique'],
  },
  {
    id: '19',
    slug: 'ingredient-selection',
    title: 'How to Select Fresh Ingredients',
    titleChinese: '如何选择新鲜食材',
    category: "Chef's Secrets",
    excerpt: 'Chef Chen shares his morning market wisdom for choosing the best produce, meat, and seafood.',
    content: 'Freshness starts at the market...',
    author: 'Chef Chen Wei',
    date: '2024-11-03',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&q=80',
    type: 'article',
    tags: ['Ingredients', 'Shopping', 'Quality'],
  },

  // COOKING TIPS (Additional)
  {
    id: '20',
    slug: 'stir-fry-basics',
    title: 'Stir-Fry Basics: High Heat, Quick Cook',
    titleChinese: '爆炒基础：高温快炒',
    category: 'Cooking Tips',
    excerpt: 'Master the fundamental technique of Chinese stir-frying for restaurant-quality results at home.',
    content: 'Stir-frying requires high heat and quick movements...',
    author: 'Chef Chen Wei',
    date: '2024-10-28',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1596040033229-a0b3b1fea2b8?w=800&q=80',
    type: 'article',
    tags: ['Stir-Fry', 'Technique', 'Basics'],
  },
];

export const categories = [
  'All',
  'Recipe History',
  'Cooking Tips',
  'Health & Nutrition',
  'Food Culture',
  'Seasonal Specials',
  "Chef's Secrets",
];

export const getStoriesByCategory = (category: string) => {
  if (category === 'All') return foodStories;
  return foodStories.filter(story => story.category === category);
};

export const getStoryBySlug = (slug: string) => {
  return foodStories.find(story => story.slug === slug);
};

export default foodStories;
